[project]
name = "cost-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AmirhosseinR9" }
]
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1",
    "passlib>=1.7.4",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
cost-management = "cost_management:main"

