"""add relationship between cost and user

Revision ID: 5f77d6d46190
Revises: ad5d3b756cc4
Create Date: 2026-09-10 16:11:33.018074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f77d6d46190'
down_revision: Union[str, Sequence[str], None] = 'ad5d3b756cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_costs_user_id_users", 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.drop_constraint("fk_costs_user_id_users", type_='foreignkey')

    # ### end Alembic commands ###
